### PR TITLE
fix: refactor EventLoopYielder

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by lierdakil** [comment]
Oh gods, why a class? You don't need a class here. Just use a closure, after all classes in JS are a lie.

**Comment by aminya** [comment]
Generally, I prefer free functions when there is no consistent state going on, and I prefer to treat JS classes like the C structs that have constructors. 

But here, there is a consistent state that needs to be kept across different calls to `yield`, and arguably, using a class is better.

From the performance point of view, I don't have a benchmark, but my gut's feelings say that a class is faster than a heap-created closure. We know that this yield closure/method isn't going to be inlined anyway, so let's use a class 😄 

I can make yield a free function passing the `started` and `lastYield` as arguments and return `lastYield` to use in the next loop, but I am not sure if this many copies worth it.

**Comment by lierdakil** [comment]
> JS classes like the C structs 

JS classes aren't at all like C structs. Objects are.

> But here, there is a consistent state that needs to be kept across different calls to yield

Which is what a closure can be used for. Which is not different from an object with a call signature.

> arguably, using a class is better.

When modelling the application domain in terms of OOP, maybe. Not doing that here, not doing that here at all. There are no other benefits, class instances are objects with prototypes, prototype resolution incurs overhead.

Using a class inflates the code and complicates the client interface with no tangible benefit. I don't see what is "better" here besides a passing resemblance with things like C# and Java.

> class is faster than a heap-created closure

All JS functions are closures, all are heap-created. That includes class "methods" (which are just functions assigned to prototype object properties). As long as you create a function _once_ there is no real difference.

> I can make yield a free function [...] but I am not sure if this many copies worth it.

There shouldn't be any difference except potential for inlining, but that's arguably moot.

***

If you want to go the optimization route, using `setImmediate` with a continuation directly can be up to an order of magnitude faster than using promises. This doesn't really matter here though, we expect to yield no more than 50 times, for which all overhead combined would total a couple milliseconds at most.

**Comment by lierdakil** [comment]
> prototype resolution incurs overhead

Spoke too soon. Synthetic tests show runtime optimizes classes/prototypes more aggressively than literally anything else I could think of: https://jsbench.me/k2kmauxlth/1 Still, the difference of 3-4% of a couple of milliseconds is entirely negligible.

**Comment by lierdakil** [comment]
Or not. Just for giggles ran the same benchmark inside Atom (via browser-plus):
image

Apparently closure is the fastest. In Atom.

... and that's why synthetic benchmarks are pretty useless and trying to optimize early is pointless.

**Comment by aminya** [comment]
The benchmarks prove that the Classes are faster than Factory functions.

image


Here is my benchmark:

```js
class EventLoopYielderClass {

  constructor(delayMs, maxTimeMs) {
    this.delayMs = delayMs
    this.maxTimeMs = maxTimeMs
    this.started = performance.now()
    this.lastYield = this.started
  }

  async yield() {
    const now = performance.now()
    if (now - this.lastYield > this.delayMs) {
      await new Promise(setImmediate)
      this.lastYield = now
    }
    if (now - this.started > this.maxTimeMs) {
      return false
    }
    return true
  }
}

function EventLoopYielderFunc(delayMs, maxTimeMs) {

  let started = performance.now()
  let lastYield = started
  return async function() {
    const now = performance.now()
    if (now - lastYield > delayMs) {
      await new Promise(setImmediate)
      lastYield = now
    }
    if (now - started > maxTimeMs) {
      return false
    }
    return true
  }
}


async function mainClass() {
  const elyClass = new EventLoopYielderClass(100, 5000)

  let temp = 0
  for (let i =0; i < 50; i++) {
    temp += heavyFunction()
    if (!(await elyClass.yield())) {
      break
    }
  }
  return temp
}

async function mainFunction() {
  const elyFunc = EventLoopYielderFunc(100, 5000)

  let temp = 0
  for (let i =0; i < 50; i++) {
    temp += heavyFunction()
    if (!(await elyFunc())) {
      break
    }
  }
  return temp
}

function heavyFunction() {
  let temp = 0
  for (let i =0; i < 100; i++) {
    temp += Math.random() ** 10
  }
  return temp
}

function benchmark() {
  let temp = 0
  console.log("benchmark factory function:")
  let t1 = performance.now()
  mainFunction().then((tempFunction) => {
    console.log(performance.now() - t1)
    
    console.log("benchmark class:")
    let t2 = performance.now()
    mainClass().then((tempClass) => {
      console.log(performance.now() - t2)

      temp = tempFunction + tempClass
    })
  })
}

benchmark()
```

setImmediate in Web if running inside browser:
```js
window.setImmediate||function(){"use strict";var e=0,t={},n=!0,a=Array.prototype.slice,i="setImmediatePolyfillMessage";function r(e){var n,r=e.data;"string"==typeof r&&0==r.indexOf(i)&&(n=t[r])&&(delete t[r],function(e){var t=e[0];switch(e.length){case 1:return t();case 2:return t(e[1]);case 3:return t(e[1],e[2])}t.apply(window,a.call(e,1))}(n))}window.setImmediate=function(){for(var a=e++,s=i+a,o=arguments.length,d=new Array(o);o--;)d[o]=arguments[o];return t[s]=d,n&&(n=!1,window.addEventListener("message",r)),window.postMessage(s,"*"),a},window.clearImmediate=function(e){delete t[i+e]}}();
```


Call the following to repeat:
```
benchmark()
```

**Comment by lierdakil** [comment]
Your benchmark is completely unreliable. I've run it (in Atom) several times, and got arbitrary results each time
image
image
image

~~Which is expected, since you're yielding to the event loop, you're basically testing whether there are pending events or not, and absolutely not what you're intending to test.~~ edit: wait, you're not yielding to the event loop, all tests take way less than 100 ms, that's my bad, I thought about my implementation which yields on creation.

**Comment by lierdakil** [comment]
Here is a little more robust benchmark based off yours: https://gist.github.com/lierdakil/b75a0c3fd0f9934fa7a193a14928094b

And here are my results (in Atom dev console):
image

The difference is negligible and well within the margin of error, with the "function" barely winning on average slightly more often in my tests (but YMMV)

**Comment by aminya** [comment]
I love the name of the gist 😄 

For JavaScript, this is what I expect at most. But if the compiler could spend more time on the code, I could see the Class code becoming faster.

**Comment by aminya** [comment]
Anyway, I have refactored the code. As you saw, it can be modified slightly to make it a factory function. I am fine with using either of these. If you want to make it a function, go ahead, and change `this.something =` to `let something =`, and return the yield function.

**Comment by lierdakil** [comment]
>  if the compiler could spend more time on the code, I could see the Class code becoming faster.

Mate, come on. There shouldn't be much difference if any on paper, whatever a compiler does. A closure is an object with a call signature. If you optimize the living soul out of both options you get the same result in both cases, namely a chunk of memory that stores a couple variables and some instructions that access that memory. Can't do much better, and can't really do much worse if your compiler does some dataflow analysis.

**Comment by lierdakil** [comment]
... i will just merge this then clean up and force push, less hassle

**Pull request merged**
